#### Generating data from a discrete model

In [1]:
# Imports
import numpy as np

In [2]:
# Settings
q = 3
n = 2

In [3]:
# Function to construct spin operator matrix
def construct_s(q):
    S = np.ones((q, q), dtype=complex)
    for i in range(q):
        for j in range(i, q):
            S[i,j] = np.exp(((i*j)*2j*np.pi) / q)
            S[j,i] = S[i,j]
    return S

In [4]:
# Perform kronecker product to get q**n x q**n matrix
S = construct_s(q)
S_matrix = np.copy(S)
for _ in range(n-1):
    S_matrix = np.kron(S_matrix, S)

The vector $\mathbf{g}$ has values for 9 different interactions:

$\mathbf{g} = (g_{00}, g_{01}, g_{02}, g_{10}, g_{11}, g_{12}, g_{20}, g_{21}, g_{22})$

##### Only zeroth interaction

In [22]:
# Must be real to get real probabilities
g = np.zeros(q**n)
g[0] = 1

In [23]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real, p.imag

(array([0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0.]))

Equal probabilities for all states if we only have $g_{00}$

#### Only first order interaction (on the second spin)

In [46]:
# Only a positive real part
g = np.zeros(q**n, dtype=complex)
g[1] = 2
g[2] = 2

In [47]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.33168898, 0.00082217, 0.00082217, 0.33168898, 0.00082217,
       0.00082217, 0.33168898, 0.00082217, 0.00082217])

Increased probability for states $\mathbf{\alpha} = \{ (0,0), (1,0), (2,0)\}$ <br>
These are states where spin 2 is equal to 0. 

In [48]:
# Only a negative real part
g = np.zeros(q**n, dtype=complex)
g[1] = -2
g[2] = -2

In [49]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.00041261, 0.16646036, 0.16646036, 0.00041261, 0.16646036,
       0.16646036, 0.00041261, 0.16646036, 0.16646036])

Decreased probability for states $\mathbf{\alpha} = \{ (0,0), (1,0), (2,0)\}$ <br>
These are states where spin 2 is equal to 0. 

In [50]:
# A positive real part with complex part (positive for 1 and negative for 2)
g = np.zeros(q**n, dtype=complex)
g[1] = 1 + 1j
g[2] = 1 - 1j

In [51]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.25835457, 0.00227569, 0.07270308, 0.25835457, 0.00227569,
       0.07270308, 0.25835457, 0.00227569, 0.07270308])

High probability for states $\mathbf{\alpha} = \{ (0,0), (1,0), (2,0)\}$ <br>
These are states where spin 2 is equal to 0. <br>

Medium probability for states $\mathbf{\alpha} = \{ (0,2), (1,2), (2,2)\}$ <br>
These are states where spin 2 is equal to 2. <br>

Low probability for states $\mathbf{\alpha} = \{ (0,1), (1,1), (2,1)\}$ <br>
These are states where spin 2 is equal to 1. <br>

In [52]:
# A positive real part with complex part (negative for 1 and positive for 2)
g = np.zeros(q**n, dtype=complex)
g[1] = 1 - 1j
g[2] = 1 + 1j

In [53]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.25835457, 0.07270308, 0.00227569, 0.25835457, 0.07270308,
       0.00227569, 0.25835457, 0.07270308, 0.00227569])

High probability for states $\mathbf{\alpha} = \{ (0,0), (1,0), (2,0)\}$ <br>
These are states where spin 2 is equal to 0. <br>

Medium probability for states $\mathbf{\alpha} = \{ (0,1), (1,1), (2,1)\}$ <br>
These are states where spin 2 is equal to 1. <br>

Low probability for states $\mathbf{\alpha} = \{ (0,2), (1,2), (2,2)\}$ <br>
These are states where spin 2 is equal to 2. <br>

In [58]:
# Only complex part (positive for 1 and negative for 2)
g = np.zeros(q**n, dtype=complex)
g[1] = 1.5j
g[2] = -1.5j

In [59]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.02296906, 0.00170928, 0.308655  , 0.02296906, 0.00170928,
       0.308655  , 0.02296906, 0.00170928, 0.308655  ])

In [62]:
# Only complex part (negative for 1 and positive for 2)
g = np.zeros(q**n, dtype=complex)
g[1] = -1.5j
g[2] = 1.5j

In [63]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.02296906, 0.308655  , 0.00170928, 0.02296906, 0.308655  ,
       0.00170928, 0.02296906, 0.308655  , 0.00170928])

##### Conclusion: Effect of the value of the interaction strength on the probability of the different states.

Real part: increases/decreases probability of the state being equal to 0 if positive/negative <br>
Imaginary part: increases/decreases the probability of the state begin equal to 1 (for $g_{01}$) if negative/positive

#### Second order interaction

##### $g_{11}$ and $g_{22}$

In [73]:
# Only a positive real part
g = np.zeros(q**n, dtype=complex)
g[4] = 2
g[8] = 2

In [74]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.33168898, 0.00082217, 0.00082217, 0.00082217, 0.00082217,
       0.33168898, 0.00082217, 0.33168898, 0.00082217])

Increased probability for states $\mathbf{\alpha} = \{ (0,0), (1,2), (2,1)\}$ <br>
(Sum is equal to 0 mod q, value of 1 in the spin operator matrix)

In [84]:
# Only a complex part (positive for g11, negative for g22)
g = np.zeros(q**n, dtype=complex)
g[4] = 1j
g[8] = -1j

In [87]:
p = np.exp(S_matrix @ g)
p /= np.sum(p)
p.real

array([0.04881033, 0.00863558, 0.27588742, 0.00863558, 0.27588742,
       0.04881033, 0.27588742, 0.04881033, 0.00863558])

Increased probability for states $\mathbf{\alpha} = \{ (0,2), (1,1), (2,0)\}$ <br>
Decreased probability for states $\mathbf{\alpha} = \{ (0,1), (1,0), (2,2)\}$ <br>

Probability increase for states with sum equal to 2 mod q <br>
Probability decrease for states with sum equal to 1 mod q


##### Conclusion:

States $\mathbf{\alpha}$ for which $\phi(\mathbf{\alpha})$ is zero, will have an increased/decreased probability if the real part of strength parameter for that interaction is positive/negative <br>
States $\mathbf{\alpha}$ for which $\phi(\mathbf{\alpha})$ is $e^{2\pi/3}$, will have an increased/decreased probability if the imaginary part of strength parameter for that interaction is negative/positive <br> 
States $\mathbf{\alpha}$ for which $\phi(\mathbf{\alpha})$ is $e^{-2\pi/3}$, will have an increased/decreased probability if the imaginary part of strength parameter for that interaction is positive/negative <br> 